name: Release Creation

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: v${{env.version}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/download/v${{env.version}}/module.json
          download: https://github.com/${{github.repository}}/releases/download/v${{env.version}}/module.zip

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./module.zip module.json image-hover.js settings.js templates/

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: "${{ github.event.repository.name }} - version ${{ env.version }}"
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: v${{env.version}}
          body: ${{ github.event.release.body }}
